# Generated by Django 5.2.7 on 2025-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extraction_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
